del /q /s *.ncb
del /q /s *.sbr
del /q /s *.obj
del /q /s *.pdb
del /q /s *.idb
del /q /s *.ib_pdb_index
del /q /s *.pch
del /q /s *.ib_tag
del /q /s *.embed.manifest
del /q /s *.user
del /q /s *.exp
del /q /s *.ilk
del /q /s *.map
del /q /s *.intermediate.manifest
del /q /s *.plg
del /q /s *.dep
del /q /s *.dmp
del /q /s *.tlog
del /q /s *.lastbuildstate
del /q /s *.log
del /q /s *.cache
del /q /s *.rsp
del /q /s *.htm
del /q /s *.res
del /q /s *.bsc
del /q /s *.ipch
del /q /s *.unsuccessfulbuild
rmdir /S /Q obj
CALL emptyfolder.bat